blank_issues_enabled: false
contact_links:
  - name: Zimbra Build Script Discussions
    url: https://github.com/ianw1974/zimbra-build-scripts/discussions
    about: For discussions related to my build scripts or Zimbra builds only!
  - name: Zimbra Forums
    url: https://forums.zimbra.org
    about: Ask about support and problems with Zimbra here.
